import { afterEach, describe, expect, it, vi } from 'vitest';

import {
  generateObjects,
  collectFqdnsToResolve,
  tryParseIpNetwork,
  tryParseIpRange,
  validateFqdn,
  safeObjName,
  resolveGroupName,
  DEFAULT_OPTIONS,
} from '../src/lib/object-helper';
import type { DnsResults, ObjectHelperOptions } from '../src/lib/object-helper';
import { resolveFqdns } from '../src/lib/dns';

// @types/node is not installed in this project, so access node:fs through
// process.getBuiltinModule (Node >= 20.16) with a minimal local declaration —
// keeps `tsc --noEmit` clean without adding dependencies.
declare const process: {
  getBuiltinModule(name: 'node:fs'): {
    readFileSync(path: URL, encoding: 'utf-8'): string;
  };
};
const fs = process.getBuiltinModule('node:fs');

function fixture(name: string): string {
  return fs.readFileSync(new URL(`./fixtures/${name}`, import.meta.url), 'utf-8');
}

const RESOLVED_AT = '2026-01-02 03:04:05Z';

/**
 * Golden parity cases. The expected files were generated by running
 * input-ideas/object-helper-v3.py with the equivalent Config overrides
 * (see the options objects below); outputs must match byte-for-byte.
 */
const goldenCases: {
  name: string;
  options: Partial<ObjectHelperOptions>;
  dns?: DnsResults;
}[] = [
  { name: 'basic', options: {} },
  { name: 'empty', options: {} },
  { name: 'explicit', options: { useExplicitNames: true } },
  { name: 'delimited', options: { nameFqdnDelimiter: ':' } },
  { name: 'input-comment', options: { useInputComment: true } },
  { name: 'explicit-comment', options: { useExplicitNames: true, useInputComment: true } },
  { name: 'per-fqdn', options: { enablePerFqdnGroup: true } },
  { name: 'no-prefix', options: { enablePrefix: false } },
  { name: 'group-prefix', options: { allObjectsGroupName: 'My {prefix}Objects' } },
  {
    name: 'flags',
    options: {
      enableColor: true,
      colorId: 5,
      enableAssociatedInterface: true,
      associatedInterface: 'wan1',
      enableAllowRouting: true,
      lowercaseFqdn: true,
      namePrefix: 'ACME',
      namePrefixDelim: '_',
    },
  },
  {
    name: 'advanced',
    options: {
      enableFabricObject: true,
      enablePassiveFqdnLearning: true,
      enableCacheTtl: true,
      cacheTtlSeconds: 600,
      ipCidrSeparator: '_',
      enableGroupComment: true,
      groupCommentTemplate: 'Generated at {resolved_at}',
      enableGroupColor: true,
      groupColorId: 7,
      enableGroupType: true,
      groupType: 'folder',
      enableGroupCategory: true,
      groupCategory: 'default',
      enableGroupFabricObject: true,
      perFqdnGroupSuffix: '-Grp',
      enablePerFqdnGroup: true,
      resolvedAt: RESOLVED_AT,
    },
  },
  { name: 'no-comment', options: { enableComment: false, useInputComment: true } },
  { name: 'no-fqdn', options: { outputFqdnObjects: false } },
  {
    name: 'templates',
    options: {
      commentTemplateFqdn: 'Host {fqdn} ({comment})',
      commentTemplateDirectIp: 'Net {ip}',
      useInputComment: true,
    },
  },
  {
    name: 'dns',
    options: { outputIpObjects: true, resolvedAt: RESOLVED_AT },
    dns: {
      'example.com': ['93.184.216.34', '93.184.216.35'],
      'fail.example.com': { error: 'resolution failed' },
      'empty.example.com': [],
    },
  },
  {
    name: 'dns-underscore',
    options: {
      outputIpObjects: true,
      outputFqdnObjects: false,
      ipObjectsUseIndex: false,
      enablePerFqdnGroup: true,
      maxIpsPerFqdn: 2,
      resolvedAt: RESOLVED_AT,
    },
    dns: { 'multi.example.com': ['1.1.1.1', '2.2.2.2', '3.3.3.3'] },
  },
];

describe('golden parity with object-helper-v3.py', () => {
  for (const { name, options, dns } of goldenCases) {
    it(`matches Python output for "${name}"`, () => {
      const input = fixture(`object-helper-${name}.input.txt`);
      const expected = fixture(`object-helper-${name}.expected.txt`);
      const result = generateObjects(input, options, dns ?? {});
      expect(result.output).toBe(expected);
    });
  }
});

describe('golden case stats and warnings', () => {
  it('reports the same counters the Python script prints for "basic"', () => {
    const input = fixture('object-helper-basic.input.txt');
    const { stats, warnings } = generateObjects(input, {});
    expect(stats).toMatchObject({
      writtenFqdn: 6,
      writtenIp: 0,
      writtenDirectIp: 5,
      writtenIpRange: 2,
      skipped: 5,
      duplicates: 2,
      dnsFailures: 0,
      total: 13,
    });
    // Long-name warning (from safe_obj_name) has no line number.
    expect(
      warnings.some(
        (w) => w.line === undefined && w.message.startsWith('Warning: object name exceeds 79'),
      ),
    ).toBe(true);
    // Duplicate warnings carry line numbers.
    expect(
      warnings.filter((w) => w.message.startsWith('Duplicate object name skipped:')),
    ).toHaveLength(2);
  });

  it('counts DNS failures in the dns fixture', () => {
    const input = fixture('object-helper-dns.input.txt');
    const { stats, warnings } = generateObjects(
      input,
      { outputIpObjects: true, resolvedAt: RESOLVED_AT },
      {
        'example.com': ['93.184.216.34', '93.184.216.35'],
        'fail.example.com': { error: 'resolution failed' },
        'empty.example.com': [],
      },
    );
    expect(stats.dnsFailures).toBe(1);
    expect(stats.writtenIp).toBe(2);
    expect(warnings.map((w) => w.message)).toEqual(
      expect.arrayContaining([
        "DNS resolve failed for 'fail.example.com': resolution failed",
        "No IPv4 A records found for 'empty.example.com'.",
        "Wildcard '*.wild.example.com' not resolvable; skipping IP objects.",
      ]),
    );
  });
});

describe('tryParseIpNetwork', () => {
  it('parses bare IPs as /32', () => {
    expect(tryParseIpNetwork('10.0.0.5')).toEqual({
      networkAddress: '10.0.0.5',
      netmask: '255.255.255.255',
      prefixlen: 32,
    });
  });

  it('masks off host bits (strict=false)', () => {
    expect(tryParseIpNetwork('10.0.0.1/24')).toEqual({
      networkAddress: '10.0.0.0',
      netmask: '255.255.255.0',
      prefixlen: 24,
    });
  });

  it('accepts netmask and hostmask notation', () => {
    expect(tryParseIpNetwork('10.30.0.0/255.255.255.0')?.prefixlen).toBe(24);
    expect(tryParseIpNetwork('10.30.0.0/0.0.0.255')?.prefixlen).toBe(24);
  });

  it('accepts /0 and /32', () => {
    expect(tryParseIpNetwork('0.0.0.0/0')).toEqual({
      networkAddress: '0.0.0.0',
      netmask: '0.0.0.0',
      prefixlen: 0,
    });
    expect(tryParseIpNetwork('255.255.255.255/32')?.networkAddress).toBe('255.255.255.255');
  });

  it('rejects anything containing a hyphen (ranges)', () => {
    expect(tryParseIpNetwork('10.0.0.1-10.0.0.9')).toBeNull();
  });

  it('rejects invalid addresses, prefixes, and masks', () => {
    expect(tryParseIpNetwork('10.0.0.999')).toBeNull();
    expect(tryParseIpNetwork('10.0.0')).toBeNull();
    expect(tryParseIpNetwork('10.0.0.0.1')).toBeNull();
    expect(tryParseIpNetwork('10.0.0.0/33')).toBeNull();
    expect(tryParseIpNetwork('10.0.0.0/')).toBeNull();
    expect(tryParseIpNetwork('010.0.0.1')).toBeNull(); // leading zero octet
    expect(tryParseIpNetwork('1.2.3.04')).toBeNull();
    expect(tryParseIpNetwork('10.0.0.0/255.0.255.0')).toBeNull(); // non-contiguous
    expect(tryParseIpNetwork('2001:db8::/32')).toBeNull(); // IPv6 not supported
    expect(tryParseIpNetwork('example.com')).toBeNull();
  });

  it('allows leading zeros in the prefix length like Python', () => {
    expect(tryParseIpNetwork('10.0.0.0/024')?.prefixlen).toBe(24);
  });
});

describe('tryParseIpRange', () => {
  it('parses full start-end ranges', () => {
    expect(tryParseIpRange('10.0.0.1-10.0.0.9')).toEqual({ start: '10.0.0.1', end: '10.0.0.9' });
    expect(tryParseIpRange(' 10.0.0.1 - 10.0.0.9 ')).toEqual({
      start: '10.0.0.1',
      end: '10.0.0.9',
    });
  });

  it('parses last-octet shorthand', () => {
    expect(tryParseIpRange('10.0.0.1-9')).toEqual({ start: '10.0.0.1', end: '10.0.0.9' });
    expect(tryParseIpRange('172.16.0.30-40')).toEqual({ start: '172.16.0.30', end: '172.16.0.40' });
    expect(tryParseIpRange('10.0.0.1-255')).toEqual({ start: '10.0.0.1', end: '10.0.0.255' });
  });

  it('allows start == end', () => {
    expect(tryParseIpRange('10.0.0.5-10.0.0.5')).toEqual({ start: '10.0.0.5', end: '10.0.0.5' });
  });

  it('rejects reversed ranges', () => {
    expect(tryParseIpRange('10.0.0.9-10.0.0.1')).toBeNull();
    expect(tryParseIpRange('10.0.0.50-45')).toBeNull();
  });

  it('rejects invalid endpoints', () => {
    expect(tryParseIpRange('10.0.0.1-999')).toBeNull();
    expect(tryParseIpRange('10.0.0.1-009')).toBeNull(); // leading-zero octet after substitution
    expect(tryParseIpRange('example.com-thing')).toBeNull();
    expect(tryParseIpRange('10.0.0.1')).toBeNull(); // no hyphen
  });
});

describe('validateFqdn', () => {
  const opts = { lowercaseFqdn: false };

  it('accepts normal and wildcard FQDNs and strips quotes', () => {
    expect(validateFqdn('example.com', opts)).toBe('example.com');
    expect(validateFqdn('"example.com"', opts)).toBe('example.com');
    expect(validateFqdn("'example.com'", opts)).toBe('example.com');
    expect(validateFqdn('*.cdn.example.net', opts)).toBe('*.cdn.example.net');
  });

  it('lowercases only when asked', () => {
    expect(validateFqdn('ExAmPle.COM', opts)).toBe('ExAmPle.COM');
    expect(validateFqdn('ExAmPle.COM', { lowercaseFqdn: true })).toBe('example.com');
  });

  it('rejects with the exact Python error messages', () => {
    expect(() => validateFqdn('', opts)).toThrow('empty fqdn');
    expect(() => validateFqdn('has space.com', opts)).toThrow('fqdn contains whitespace');
    expect(() => validateFqdn('https://example.org/path', opts)).toThrow(
      'fqdn looks like a URL; provide host only (e.g., example.com)',
    );
    expect(() => validateFqdn('example.com/path', opts)).toThrow(
      'fqdn looks like a URL; provide host only (e.g., example.com)',
    );
    expect(() => validateFqdn('singlelabel', opts)).toThrow(
      'fqdn must contain a dot (e.g., example.com)',
    );
    expect(() => validateFqdn('double..dot.com', opts)).toThrow('fqdn has an empty label (..)');
    expect(() => validateFqdn(`${'a'.repeat(64)}.com`, opts)).toThrow('fqdn label too long (>63)');
    expect(() => validateFqdn('-lead.example.com', opts)).toThrow(
      "fqdn label cannot start/end with '-'",
    );
    expect(() => validateFqdn('trail-.example.com', opts)).toThrow(
      "fqdn label cannot start/end with '-'",
    );
    expect(() => validateFqdn('bad_label.example.com', opts)).toThrow(
      "fqdn label has invalid chars: 'bad_label'",
    );
  });
});

describe('safeObjName', () => {
  it('strips quotes and collapses whitespace', () => {
    const warnings: string[] = [];
    const warn = (m: string) => warnings.push(m);
    expect(safeObjName('  a  "b"\nc  ', warn)).toBe('a b c');
    expect(warnings).toHaveLength(0);
  });

  it('throws on empty names', () => {
    expect(() => safeObjName('  " " ', () => {})).toThrow('empty object name');
  });

  it('warns (but keeps) names over 79 chars', () => {
    const warnings: string[] = [];
    const long = 'x'.repeat(85);
    const result = safeObjName(long, (m) => warnings.push(m));
    expect(result).toBe(long);
    expect(warnings).toEqual([
      `Warning: object name exceeds 79 chars and will be rejected by FortiGate: '${long}'`,
    ]);
  });
});

describe('resolveGroupName', () => {
  it('replaces {prefix} with prefix+delim', () => {
    expect(resolveGroupName('My {prefix}Objects', {})).toBe('My Prefix-Objects');
  });

  it('auto-prepends an active prefix when no placeholder', () => {
    expect(resolveGroupName('My Group', {})).toBe('Prefix-My Group');
  });

  it('leaves the name alone with prefix disabled', () => {
    expect(resolveGroupName('My Group', { enablePrefix: false })).toBe('My Group');
    expect(resolveGroupName('My {prefix}Objects', { enablePrefix: false })).toBe('My Objects');
  });
});

describe('duplicate suppression', () => {
  it('suppresses repeated names across entry types and counts them', () => {
    const input = 'example.com\nexample.com\n10.0.0.1\n10.0.0.1\n';
    const { output, stats, warnings } = generateObjects(input);
    expect(stats.duplicates).toBe(2);
    expect(stats.total).toBe(2);
    expect((output.match(/edit "Prefix-example\.com"/g) ?? []).length).toBe(1);
    expect(warnings.filter((w) => w.message.includes('Duplicate object name'))).toHaveLength(2);
    expect(warnings.find((w) => w.message === "Duplicate object name skipped: 'Prefix-example.com'")?.line).toBe(2);
  });

  it('suppresses a direct IP colliding with an explicit name', () => {
    const input = 'same\nexample.com\nsame\n10.0.0.1\n';
    const { stats } = generateObjects(input, { useExplicitNames: true });
    expect(stats.duplicates).toBe(1);
    expect(stats.total).toBe(1);
  });
});

describe('input format warnings', () => {
  it('warns about odd line counts in pair mode', () => {
    const { warnings } = generateObjects('name\nexample.com\norphan\n', {
      useExplicitNames: true,
    });
    expect(warnings[0].message).toBe(
      "Warning: input has an odd number of non-empty lines (3). The last line will be ignored: 'orphan'",
    );
  });

  it('warns about non-multiple-of-3 counts in explicit+comment mode', () => {
    const { warnings } = generateObjects('a\nexample.com\ncomment\nb\n', {
      useExplicitNames: true,
      useInputComment: true,
    });
    expect(warnings[0].message).toBe(
      'Warning: input has 4 non-empty lines, which is not a multiple of 3 (name / fqdn / comment). Trailing incomplete group will be ignored.',
    );
  });

  it('warns about missing delimiters with a Python-repr delimiter', () => {
    const { warnings } = generateObjects('nodelim.example.com\n', { nameFqdnDelimiter: ':' });
    expect(warnings[0]).toEqual({
      line: 1,
      message: "No delimiter ':' found; skipping: 'nodelim.example.com'",
    });
  });
});

describe('DNS-dependent generation with mocked results', () => {
  const dns: DnsResults = {
    'a.example.com': ['1.1.1.1', '2.2.2.2'],
    'b.example.com': { error: 'timed out' },
  };

  it('emits /32 objects with the ip comment template', () => {
    const { output, stats } = generateObjects(
      'a.example.com\n',
      { outputIpObjects: true, resolvedAt: RESOLVED_AT },
      dns,
    );
    expect(output).toContain('edit "Prefix-a.example.com-IP-1"\n');
    expect(output).toContain('set subnet 1.1.1.1 255.255.255.255\n');
    expect(output).toContain(
      `set comment "Resolved from a.example.com | ip=1.1.1.1 | resolved_at=${RESOLVED_AT}"\n`,
    );
    expect(stats.writtenIp).toBe(2);
  });

  it('treats a missing cache entry as "no A records"', () => {
    const { warnings, stats } = generateObjects(
      'unknown.example.com\n',
      { outputIpObjects: true },
      dns,
    );
    expect(stats.dnsFailures).toBe(0);
    expect(warnings.some((w) => w.message === "No IPv4 A records found for 'unknown.example.com'.")).toBe(true);
  });

  it('caps resolved IPs at maxIpsPerFqdn', () => {
    const { stats } = generateObjects(
      'a.example.com\n',
      { outputIpObjects: true, maxIpsPerFqdn: 1, resolvedAt: RESOLVED_AT },
      dns,
    );
    expect(stats.writtenIp).toBe(1);
  });

  it('never emits IP objects when outputIpObjects is off', () => {
    const { output } = generateObjects('a.example.com\n', {}, dns);
    expect(output).not.toContain('-IP-');
  });
});

describe('collectFqdnsToResolve', () => {
  it('collects only resolvable FQDNs, deduped', () => {
    const input = [
      'example.com',
      'example.com',
      '*.wild.example.com',
      '10.0.0.1',
      '10.0.0.0/24',
      '10.0.0.1-9',
      'https://url.example.com/x',
      'b.example.org',
    ].join('\n');
    expect(collectFqdnsToResolve(input)).toEqual(['example.com', 'b.example.org']);
  });

  it('uses the value column in delimited mode', () => {
    expect(collectFqdnsToResolve('n1:example.com\nn2:10.0.0.1', { nameFqdnDelimiter: ':' })).toEqual([
      'example.com',
    ]);
  });
});

describe('bulk comment', () => {
  /** Comment lines emitted for address objects, in output order. */
  function comments(output: string): string[] {
    return [...output.matchAll(/^set comment "(.*)"$/gm)].map((m) => m[1]);
  }

  it('is off by default, leaving output unchanged', () => {
    const input = 'example.com\n';
    expect(generateObjects(input, {}).output).toBe(
      generateObjects(input, { bulkComment: '' }).output,
    );
  });

  it('stands alone when the object has no other comment', () => {
    const { output } = generateObjects('example.com\n', { bulkComment: 'Ticket 123' });
    expect(comments(output)).toContain('Ticket 123');
  });

  it('is appended to an existing input comment', () => {
    const { output } = generateObjects('example.com\nfrom the vendor\n', {
      useInputComment: true,
      bulkComment: 'Ticket 123',
    });
    expect(comments(output)).toContain('from the vendor | Ticket 123');
  });

  it('is appended to a rendered template comment', () => {
    const { output } = generateObjects('example.com\n', {
      commentTemplateFqdn: 'fqdn={fqdn}',
      bulkComment: 'Ticket 123',
    });
    expect(comments(output)).toContain('fqdn=example.com | Ticket 123');
  });

  it('honours a custom separator', () => {
    const { output } = generateObjects('example.com\nvendor\n', {
      useInputComment: true,
      bulkComment: 'Ticket 123',
      bulkCommentSeparator: ' — ',
    });
    expect(comments(output)).toContain('vendor — Ticket 123');
  });

  it('applies to every object in the list', () => {
    const { output } = generateObjects('a.example\nb.example\nc.example\n', {
      bulkComment: 'Ticket 123',
    });
    const found = comments(output).filter((c) => c.includes('Ticket 123'));
    expect(found).toHaveLength(3);
  });

  it('is ignored when comments are disabled', () => {
    const { output } = generateObjects('example.com\n', {
      enableComment: false,
      bulkComment: 'Ticket 123',
    });
    expect(output).not.toContain('set comment');
  });

  it('ignores a whitespace-only value and trims the text', () => {
    expect(generateObjects('example.com\n', { bulkComment: '   ' }).output).not.toContain(
      'set comment',
    );
    const { output } = generateObjects('example.com\n', { bulkComment: '  Ticket 123  ' });
    expect(comments(output)).toContain('Ticket 123');
  });

  it('sanitizes double quotes like other comments', () => {
    const { output } = generateObjects('example.com\n', { bulkComment: 'say "hi"' });
    expect(comments(output)).toContain("say 'hi'");
  });

  it('applies to direct IP and range objects too', () => {
    const { output } = generateObjects('10.0.0.0/24\n10.1.1.1-10.1.1.9\n', {
      bulkComment: 'Ticket 123',
    });
    const found = comments(output).filter((c) => c.includes('Ticket 123'));
    expect(found).toHaveLength(2);
  });
});

describe('defaults', () => {
  it('mirror the Python Config dataclass', () => {
    expect(DEFAULT_OPTIONS).toMatchObject({
      enablePrefix: true,
      namePrefix: 'Prefix',
      namePrefixDelim: '-',
      outputFqdnObjects: true,
      outputIpObjects: false,
      enableAllObjectsGroup: true,
      allObjectsGroupName: 'Generated Objects',
      enablePerFqdnGroup: false,
      enableComment: true,
      commentTemplateFqdn: '',
      commentTemplateIp: 'Resolved from {fqdn} | ip={ip} | resolved_at={resolved_at}',
      commentTemplateDirectIp: '',
      maxIpsPerFqdn: 20,
      dnsTimeoutSeconds: 3.0,
      dnsWorkers: 10,
      ipCidrSeparator: '/',
      ipObjectsUseIndex: true,
      ipObjectSuffix: '-IP-',
      perFqdnGroupSuffix: '-Group',
      cacheTtlSeconds: 300,
      associatedInterface: 'port1',
    });
  });
});

describe('resolveFqdns (mocked fetch)', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  function dohResponse(body: unknown, ok = true, status = 200): Response {
    return {
      ok,
      status,
      json: async () => body,
    } as unknown as Response;
  }

  it('returns sorted unique capped A records from Cloudflare', async () => {
    const fetchMock = vi.fn().mockResolvedValue(
      dohResponse({
        Status: 0,
        Answer: [
          { type: 1, data: '9.9.9.9' },
          { type: 1, data: '1.1.1.1' },
          { type: 1, data: '9.9.9.9' },
          { type: 5, data: 'cname.example.com.' },
        ],
      }),
    );
    vi.stubGlobal('fetch', fetchMock);
    const results = await resolveFqdns(['example.com'], { maxIps: 20 });
    expect(results['example.com']).toEqual(['1.1.1.1', '9.9.9.9']);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(String(fetchMock.mock.calls[0][0])).toContain('cloudflare-dns.com');
  });

  it('falls back to Google when Cloudflare fails', async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce(dohResponse({}, false, 500))
      .mockResolvedValueOnce(dohResponse({ Status: 0, Answer: [{ type: 1, data: '8.8.8.8' }] }));
    vi.stubGlobal('fetch', fetchMock);
    const results = await resolveFqdns(['example.com']);
    expect(results['example.com']).toEqual(['8.8.8.8']);
    expect(String(fetchMock.mock.calls[1][0])).toContain('dns.google');
  });

  it('records an error entry when both endpoints fail', async () => {
    const fetchMock = vi.fn().mockResolvedValue(dohResponse({ Status: 3 }));
    vi.stubGlobal('fetch', fetchMock);
    const results = await resolveFqdns(['nxdomain.example.com']);
    expect(results['nxdomain.example.com']).toEqual({ error: 'DNS error status 3' });
  });
});
