import type { Warning } from '../../types';

/** FortiGate address object name hard limit. */
export const MAX_OBJ_NAME_LEN = 79;

/**
 * DNS resolution results injected into `generateObjects`:
 * fqdn -> list of IPv4 addresses, or an error marker.
 */
export type DnsResults = Record<string, string[] | { error: string }>;

/**
 * All options for the Object Helper generator. Field names and defaults
 * mirror the `Config` dataclass of `input-ideas/object-helper-v3.py`.
 */
export interface ObjectHelperOptions {
  // --- Object name prefix ---
  enablePrefix: boolean;
  namePrefix: string;
  namePrefixDelim: string;

  // --- What to emit ---
  outputFqdnObjects: boolean;
  outputIpObjects: boolean;

  // --- Groups ---
  enableAllObjectsGroup: boolean;
  allObjectsGroupName: string;
  enablePerFqdnGroup: boolean;

  // --- Object appearance ---
  enableComment: boolean;
  commentTemplateFqdn: string;
  commentTemplateIp: string;
  commentTemplateDirectIp: string;
  /**
   * Text added to every address object's comment. Appended after whatever
   * comment the entry already has, or used on its own when it has none.
   * Empty disables it. Requires `enableComment`.
   */
  bulkComment: string;
  /** Joins an existing comment and `bulkComment`. */
  bulkCommentSeparator: string;
  enableColor: boolean;
  colorId: number;

  // --- Input format ---
  useExplicitNames: boolean;
  useInputComment: boolean;
  nameFqdnDelimiter: string;
  lowercaseFqdn: boolean;

  // --- Extra object options ---
  enableAllowRouting: boolean;
  enableFabricObject: boolean;
  enablePassiveFqdnLearning: boolean;
  enableCacheTtl: boolean;
  cacheTtlSeconds: number;
  enableAssociatedInterface: boolean;
  associatedInterface: string;

  // --- Output structure ---
  startWithConfigFirewallAddress: boolean;
  endConfigFirewallAddress: boolean;

  // --- DNS resolution ---
  maxIpsPerFqdn: number;
  dnsTimeoutSeconds: number;
  dnsWorkers: number;

  // --- Direct IP / CIDR object naming ---
  ipCidrSeparator: string;

  // --- Resolved IP object naming ---
  ipObjectsUseIndex: boolean;
  ipObjectSuffix: string;

  // --- Group details ---
  perFqdnGroupSuffix: string;
  enableGroupComment: boolean;
  groupCommentTemplate: string;
  enableGroupColor: boolean;
  groupColorId: number;
  enableGroupType: boolean;
  groupType: string;
  enableGroupCategory: boolean;
  groupCategory: string;
  enableGroupFabricObject: boolean;

  /**
   * Timestamp used for the {resolved_at} placeholder, formatted
   * "YYYY-MM-DD HH:MM:SSZ". Injectable for deterministic tests;
   * defaults to the current UTC time.
   */
  resolvedAt?: string;
}

/** Defaults identical to the Python Config dataclass. */
export const DEFAULT_OPTIONS: ObjectHelperOptions = {
  enablePrefix: true,
  namePrefix: 'Prefix',
  namePrefixDelim: '-',

  outputFqdnObjects: true,
  outputIpObjects: false,

  enableAllObjectsGroup: true,
  allObjectsGroupName: 'Generated Objects',
  enablePerFqdnGroup: false,

  enableComment: true,
  commentTemplateFqdn: '',
  commentTemplateIp: 'Resolved from {fqdn} | ip={ip} | resolved_at={resolved_at}',
  commentTemplateDirectIp: '',
  bulkComment: '',
  bulkCommentSeparator: ' | ',
  enableColor: false,
  colorId: 0,

  useExplicitNames: false,
  useInputComment: false,
  nameFqdnDelimiter: '',
  lowercaseFqdn: false,

  enableAllowRouting: false,
  enableFabricObject: false,
  enablePassiveFqdnLearning: false,
  enableCacheTtl: false,
  cacheTtlSeconds: 300,
  enableAssociatedInterface: false,
  associatedInterface: 'port1',

  startWithConfigFirewallAddress: true,
  endConfigFirewallAddress: true,

  maxIpsPerFqdn: 20,
  dnsTimeoutSeconds: 3.0,
  dnsWorkers: 10,

  ipCidrSeparator: '/',

  ipObjectsUseIndex: true,
  ipObjectSuffix: '-IP-',

  perFqdnGroupSuffix: '-Group',
  enableGroupComment: false,
  groupCommentTemplate: 'Generated by resolver script at {resolved_at}',
  enableGroupColor: false,
  groupColorId: 0,
  enableGroupType: false,
  groupType: 'default',
  enableGroupCategory: false,
  groupCategory: 'default',
  enableGroupFabricObject: false,
};

/** Fill unspecified options with the Python-equivalent defaults. */
export function withDefaults(options: Partial<ObjectHelperOptions> = {}): ObjectHelperOptions {
  return { ...DEFAULT_OPTIONS, ...options };
}

export interface ObjectHelperStats {
  writtenFqdn: number;
  writtenIp: number;
  writtenDirectIp: number;
  writtenIpRange: number;
  skipped: number;
  duplicates: number;
  dnsFailures: number;
  total: number;
  resolvedAt: string;
}

export interface GenerateResult {
  output: string;
  warnings: Warning[];
  stats: ObjectHelperStats;
}

/** Current UTC time formatted like the Python RESOLVED_AT ("YYYY-MM-DD HH:MM:SSZ"). */
export function defaultResolvedAt(now: Date = new Date()): string {
  const p = (n: number) => String(n).padStart(2, '0');
  return (
    `${now.getUTCFullYear()}-${p(now.getUTCMonth() + 1)}-${p(now.getUTCDate())} ` +
    `${p(now.getUTCHours())}:${p(now.getUTCMinutes())}:${p(now.getUTCSeconds())}Z`
  );
}
